name: Deploy to Vercel

on:
  push:
    branches:   
      - main  # Change this to your main branch name

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install NPM
        working-directory: final-practice
        run: npm install 

      - name: Install dependencies
        working-directory: final-practice
        run: npm install --frozen-lockfile

      - name: Build
        working-directory: final-practice
        run: npm build  # Adjust this command based on your project setup

      - name: Deploy to Vercel
        working-directory: final-practice
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
