name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and PNPM
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: practice-two
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to Vercel
        working-directory: practice-two
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
