name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and PNPM
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: practice-two
        run: pnpm build  # Adjust this command based on your project setup

      - name: Deploy to Vercel
        working-directory: practice-two
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
